Add types
Meteor-Community-Packages/meteor-collection2 pull request #459
Opened 2024-11-07 23:00 UTC by merlinstardust

**Table of Contents**  *generated with [DocToc](https://github.com/thlorenz/doctoc)*

- [What](#what)
- [Why](#why)

## What

Adds TypeScript Support. Handles #458

## Why

Meteor has added TypeScript Support so this package should support it as well

2024-11-10 19:09 UTC, harryadel commented
Is this considered done?

2024-11-12 01:32 UTC, StorytellerCZ requested changes
Since the package is not Typescript I'm not sure if this will be enough, but at least it is a start.

2024-11-12 01:32 UTC, StorytellerCZ commented on package/collection2/package.js
> +  name: 'collection2local',
Please reverse the package name.

2024-11-21 19:30 UTC, jankapunkt approved these changes

2024-11-21 19:30 UTC, merged